name: Pull request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  # 1er job, test unitaire
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: execution des tests
        run: mvn test
  # 2eme job, build app
  build-app:
    needs: test-unitaire
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: creation du jar
        run: mvn package
      - name: upload du jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar