name: Pull request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  # 1er job, test unitaire
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: execution des tests
        run: mvn test
  # 2eme job, build app
  build-app:
    needs: test-unitaire
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: creation du jar
        run: mvn package
      - name: upload du jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar
  # 3eme job, on dockerise l'application
  build-docker:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation du jar
        uses: actions/download-artifact@v2
        with:
          name: app.jar
      - name: Install QEMU Docker
        uses: docker/setup-qemu-action@v1
      - name: Install BuildX docker
        uses: docker/setup-buildx-action@v1
      - name: Connection à Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build et push mon image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bricedo/testdemo:latest
