name: Workflow push
on:
  push:
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation de java
        uses: actions/setup-java
        with:
          distribution: adopt
          java-version: 11
      - name: execution des tests
        run: mvn test